### ISSUE TITLE
Add a workaround for "JSON cannot hold BLOB values" error

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-json-html#4]
If you attempt to do this:
```
select id, json_object(
    "href", url, "label", text
) from mytable;
```
But the `text` column contains certain characters, SQLite throws this error:

    JSON cannot hold BLOB values

Maybe provide a utility SQL function to work around this, something like `json_string(value)`?

**Comment by simonw** [comment]
Here's a 1x1 transaprent gif converted to SQLite hex notation:
```
>>> b"GIF89a\x01\x00\x01\x00\x80\x00\x00\x00\x00\x00\xff\xff\xff!\xf9\x04\x01\x00\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x01D\x00;".hex()
'47494638396101000100800000000000ffffff21f90401000000002c000000000100010000020144003b'
```
So in SQLite that would be:

    select x'47494638396101000100800000000000ffffff21f90401000000002c000000000100010000020144003b'

**Comment by simonw** [comment]
That doesn't replicate the bug though: https://datasette-json-html-demo-j7hipcg4aq-uc.a.run.app/demo?sql=select+%27%7B%0D%0A++++%22href%22%3A+%22https%3A%2F%2Fsimonwillison.net%2F%22%2C%0D%0A++++%22label%22%3A+%27+%7C%7C+X%2747494638396101000100800000000000ffffff21f90401000000002c000000000100010000020144003b%27+%7C%7C+%27%0D%0A%7D%27

<img width="1198" alt="demo__select__{__href____https___simonwillison_net_____label________X_47494638396101000100800000000000ffffff21f90401000000002c000000000100010000020144003b_______}_" src="https://user-images.githubusercontent.com/9599/89743283-7862b980-da56-11ea-8618-314a26a773cc.png">

**Comment by simonw** [comment]
I can't replicate this. Will re-open if it shows up again.

**Comment by furkanpaligu** [comment]
I have a problem where I need to display the characters in the label field correctly. I can display them like the one on the comment with <?> but I can not obtain the full label string. How may I do that ?
